# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightControl', '0002_remove_rooms_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_logo',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
