# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightControl', '0003_rooms_room_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchs',
            name='switch',
            field=models.CharField(max_length=20),
        ),
    ]
