# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightControl', '0006_switch_gpio_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='gpio_pin',
        ),
    ]
